components:
  csiHyperstack:
    imagePullPolicy: Always
    image: ghcr.io/nexgencloud/csi-hyperstack/csi
    tag: latest
  nodeDriverRegistrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
  csiAttacher:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
  csiProvisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
  csiResizer:
    image: registry.k8s.io/sig-storage/csi-resizer:v1.11.1
  csiSnapshotter:
    image: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1

hyperstack:
  apiAddress: "https://infrahub-api.nexgencloud.com/v1"

storageClass:
  enabled: true
  name: "csi-hyperstack"
  volumeBindingMode: "Immediate"
  reclaimPolicy: "Delete"
